# Generated by Django 2.0.5 on 2018-05-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
        ('polls', '0003_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='댓글')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m/%d/', verbose_name='이미지')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customuser.CustomUser')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
